### ISSUE TITLE
eslint package version conflict

### ISSUE THREAD

**Issue by jcw** [killercup/cycle-webpack-starter#1]
Nice starter project! I had to change `package.json` to use eslint 0.8.0 to avoid this error:

```
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/Cellar/iojs/2.4.0/bin/iojs" "/usr/local/bin/npm" "i"
npm ERR! node v2.4.0
npm ERR! npm  v2.13.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint@1.0.0-rc-2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-cycle@1.0.0 wants eslint@>=0.8.0
npm ERR! peerinvalid Peer eslint-plugin-react@3.0.0 wants eslint@>=0.8.0 || ~1.0.0-rc-0
```

Not sure it's the best way out, but it got me past that npm error and let me try the demo.

**Comment by killercup** [comment]
Interesting. When updating to the 1.0 rc2 my local npm3 didn't say anything.
You probably shouldn't downgrade as far as 0.8. Just have a look at one of
the last few commits where I increased ESLint's version.
Jean-Claude Wippler notifications@github.com schrieb am Fr., 24. Juli
2015 um 12:50:

**Comment by jcw** [comment]
Aha, it might be an npm 2 vs 3 difference, then.

Eslint 0.24.1 passes, but `npm run lint` fails with "Failed at the cycle-test@1.0.0 lint script 'eslint .'."
I'm fine with either downgrade for now, just so I can keep playing with this.
Thanks. Great fun trying this stuff out, btw.

**Comment by jcw** [comment]
Some errors remain, even after removing a couple of settings from `.eslintrc`. Oh well.
Leaving this issue open for now, in case you want to chase the original "peerinvalid" error further.
Feel free to close, of course.

**Comment by killercup** [comment]
A global install should not be necessary. (I also don't like to install
_anything_ globally if I can help it). If the plugins don't work with the
1.0 RC, I'll revert the commit to use the latest 'stable' version (and
maybe send some PR to the plugin repos).

Jean-Claude Wippler notifications@github.com schrieb am Fr., 24. Juli
2015 um 19:12:

**Comment by killercup** [comment]
So, just to confirm it, this is a "WARN" with npm3.

I'm removing the cycle plugin (haven't used it myself anyway) and adding a forked version of eslint-plugin-babel until babel/eslint-plugin-babel#5 is merged.

_Edit:_ babel/eslint-plugin-babel#5 was just merged. Waiting for a release on npm.

**Comment by killercup** [comment]
@jcw FYI, I just pushed updates for nearly every dependency. All the ESLint thingies now use ESLint 1.x.
