### ISSUE TITLE
npm start is not working this morning

### ISSUE THREAD

**Issue by HighOnDrive** [killercup/cycle-webpack-starter#5]
Thanks for the great starter. It was working for me last night but something changed and I'm getting the following error when I run the npm start script:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.3
3 info using node@v4.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart cycle-webpack-starter@0.1.0
6 info start cycle-webpack-starter@0.1.0
7 verbose unsafe-perm in lifecycle true
8 info cycle-webpack-starter@0.1.0 Failed to exec start script
9 verbose stack Error: cycle-webpack-starter@0.1.0 start: `webpack-dev-server --config webpack-dev.config.babel.js --progress`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid cycle-webpack-starter@0.1.0
11 verbose cwd /Users/SM/DEV-projects/cycle-webpack-starter-feature-travis
12 error Darwin 14.5.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.1.0
15 error npm  v2.14.3
16 error code ELIFECYCLE
17 error cycle-webpack-starter@0.1.0 start: `webpack-dev-server --config webpack-dev.config.babel.js --progress`
17 error Exit status 1
18 error Failed at the cycle-webpack-starter@0.1.0 start script 'webpack-dev-server --config webpack-dev.config.babel.js --progress'.
18 error This is most likely a problem with the cycle-webpack-starter package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server --config webpack-dev.config.babel.js --progress
18 error You can get their info via:
18 error     npm owner ls cycle-webpack-starter
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by killercup** [comment]
Interesting. I don't really understand the stack trace about EventEmitter failing.

> It was working for me last night but something changed and I'm getting the following error

Do you have any idea what changed? Did you pull a new version?

Can removing the `node_modules` folder and running `npm install` again fix this?

Meanwhile, it works for me, on OS X 10.10 with

```
npm info using npm@3.3.6
npm info using node@v4.1.1
```

**Comment by HighOnDrive** [comment]
At first I had run it fine and then was tweaking it's layout and I messed something up. That was when I got a fresh copy and also noticed there had been a new merge made to the repo. Then when I ran the new copy I got the error I listed above. I had tried removing `node_modules` and running `npm install` as well.

So now, even after the upgrade to El Capitan last night it works once again, both server and build. This is with a fresh copy downloaded just now.

Your starter is quite nice and looks like it is maintained. So I'm thinking on how to best use it in my project so that I can always use the latest version of your starter. Essentially, I could fetch a new starter project and just remove the `app` folder and drop in my own `app` folder, full of the contents of my specific project. Except there is a problem, the `vendor.js` and the `helpers` need to be moved out of `app`.

Since these two items are really webpack related maybe they can be moved into the webpack area at the bottom of the project directory? Also. since there are so many webpack related files maybe they could all be placed into one neat folder? That sure would tidy things up a bit and make using the starter as a project base more efficient.

**Comment by killercup** [comment]
(I'm closing this issue, since it now works for you.)

> Your starter is quite nice and looks like it is maintained. So I'm thinking on how to best use it in my project so that I can always use the latest version of your starter.

Thanks! I'm glad you like it.

You shouldn't need to worry about using the latest version of this starter pack—just pick the current one and begin tweaking it to your liking! The 'biggest' updates to the starter are just updating dependencies and you can probably just copy-paste them into your project (e.g. an updated ESLint config).

I'm also pretty sure you'll want to add a lot of stuff to the webpack configs so they work for you, e.g. for handling tests, stylesheets and other asset files.

> Except there is a problem, the vendor.js and the helpers need to be moved out of app.

Both files should be specific to your app, these are just suggestions (and really small).

> since there are so many webpack related files maybe they could all be placed into one neat folder? That sure would tidy things up a bit and make using the starter as a project base more efficient.

There are 3 files… But feel free to move them somewhere, you'll only need to update the npm scripts.

> That sure would tidy things up a bit and make using the starter as a project base more efficient.

It's not a project base, it's a starter kit! :smile: Feel free to move stuff around and adjust it to your needs!

**Comment by HighOnDrive** [comment]
Awesome :+1:
